# ---------------------------------------------------------------
n_surrogates: 20 # graphs to sample per dataset
overwrite: false # set true to ignore cached results
# privacy levels
eps: [1, 3, 5]
delta: [1e-4]

metrics:
  - shortest_path
  - avg_path_length
  - degree
  - clustering
  - avg_clustering
  - eigen_val 
  - eigen_centrality
  - infomap
  - leiden
  - assortativity
  #- embedding_node2vec
  - embedding_prone
