# ---------------------------------------------------------------
n_surrogates: 10 # graphs to sample per dataset
overwrite: true # set true to ignore cached results
# privacy levels
eps: [0.1, 1, 3]
delta: [1e-4]

metrics:
  - shortest_path
  - avg_path_length
  - degree
  - clustering
  - avg_clustering
  - eigen_val 
  - eigen_centrality
  - infomap
  - leiden
  - assortativity
  #- embedding_node2vec
  - embedding_prone
